Feat: support
7-7-2/DDocker_BE pull request #124
Opened 2024-05-22 13:56 UTC by cuconveniencestore

## 🪴 작업내용
- Support
- Notice && FAQ
- #### 🪴 closed #123

2024-05-22 15:41 UTC, hookor requested changes

2024-05-22 15:41 UTC, hookor commented on controllers/support-controller.js
> +    return;
캐시 받기만 하고 리턴 삼항연산자 처리가 없는 것 같아용 수정부탁드립니다!!

2024-05-24 06:52 UTC, cuconveniencestore commented on controllers/support-controller.js
> +    return;
수정했습니다!!

2024-05-27 05:54 UTC, hookor approved these changes
**수고하셨습니다!!**

2024-05-27 05:54 UTC, merged